### ISSUE TITLE
mbtiles 数据需要构造成什么样子才能直接套用 mapbox studio 产出的样式？

### ISSUE THREAD

**Issue by glud123** [jingsam/foxgis-server-lite#29]
你好，
之前有发过邮件沟通，感谢回复😊
### 预期
我现在希望创建一个跟 mapbox 官方类似的离线地图，最好是能直接套用mapbox studio所产出的 style 文件
### 当下
已经使用 foxgis-server-lite 成功的创建了瓦片服务，通过 mapbox-gl 也能正常渲染出地图内容，地图所呈现的样式达不到预期（很丑😞）
### 问题
通过分析 mapbox studio 产出的 style 文件中 `sources` 只包含了三个数据源 "mapbox://mapbox.mapbox-traffic-v1"、"mapbox://mapbox.mapbox-incidents-v1"、"composite"。"composite" 数据源中包含了多个 layer，如 “road”、“building”、“water” 等等，我理解的只需要处理好 `composite` 这个数据源中每个图层的样式就能保证 mapbox 可以渲染出漂亮的地图。

但是我现在遇到的问题是，我在 [OpenStreetMap](http://download.geofabrik.de/index.html) 下载的`.shp`  文件所转换出的`.mbtiles文件`与 "composite" 数据源中所列出的`layer` 不是完全匹配，而且我现在不知道该如何准确的进行匹配。
>`.shp` 文件我是通过 `ogr2ogr` 转换成 `.geojson` 文件，又将 `.geojson` 文件通过 `tippecanoe` 转换成各自的 `.mbtiles` 文件

核心诉求：怎么处理mbtiles 数据才能套用mapbox studio 产出的 style 文件

**Comment by jingsam** [comment]
你需要有一套mapbox streets的数据，这基本上很困难。你可以看看https://openmaptiles.org/这个项目，他有样式以及配套的瓦片

**Comment by glud123** [comment]
> 你需要有一套mapbox streets的数据，这基本上很困难。你可以看看 https://openmaptiles.org/ 这个项目，他有样式以及配套的瓦片

感谢，这可能是我想要的，我先尝试一下。

**Comment by lm1720755472** [comment]
请问大佬，我也用的OSM的开源数据，转换为mbtiles数据的方法跟你一模一样，但是我用maobox GL渲染的时候显示“tile does not exist”，你没有遇到这种问题啊？我怀疑是我的mbtiles数据有问题，没有被getTile这个函数识别出来。

**Comment by glud123** [comment]
> 请问大佬，我也用的OSM的开源数据，转换为mbtiles数据的方法跟你一模一样，但是我用maobox GL渲染的时候显示“tile does not exist”，你没有遇到这种问题啊？我怀疑是我的mbtiles数据有问题，没有被getTile这个函数识别出来。

这是我离线地图基于 foxgis-server-lite 完整的搭建过程，你可以作为参考 https://juejin.cn/post/6884144929098956813
